<!DOCTYPE html>
<head>

<title> WT_k </title>

</head>

<body>

<center>

<h1> Welcome to the 1st lab classa </h1>

<h1> lets make aa registration form </h1>

</center>
<p> I am a student of this class, <br> in this class I will learn html,css,js and many money_format

Enter your name :
<input type ="text"> <br><br>

Enter your age :
<input type = "text"> <br> <br>

Enter your DOB :
<input type = "date"> <br> <br>

Enter your preffered language:
<input type ="radio"> Bangla
<input type ="radio"> English

Enter your preffered language:
<input type ="checkbox"> Bangla
<input type ="radio"> English
   
<center>
    <inout type ="submit">

<center>



</body>
