git commit <!DOCTYPE html>
<head>

<title> WT_k </title>

</head>

<body>

<center>

<h1 style =color:blue> Clinic Patient Registration </h1>


</center>


Full Name: <br>
<input type ="text" > <br><br>

Age : <br>
<input type = "text"> <br> <br>

Phone number: <br>
<input type = "tel"> <br> <br>

Email Address: <br>
<input type = "email"> <br> <br>

Insurance Provider: <br>
    <select name="insurance">
      <option> Select Provider </option>
      <option>Company A</option>
      <option>Company B</option>
      <option>Company C</option>
    </select>
    <br><br>

Insurance Policy Number: <br>
<input type = "text"> <br> <br>

<center>

<h2 style =color:blue> Additional Information </h2>


</center>

Username: <br>
<input type ="text"> <br><br>

Password: <br>
<input type ="password"> <br><br>

Confirm Password: <br>
<input type ="password"> <br><br>

<center>
   


<center>



</body>
